[package]
name = "rust-ddr"
version = "0.1.0"
authors = ["DerpyCrabs <derpycrabs@gmail.com>"]
edition = "2018"

[dependencies]
quicksilver = "*"
osu_format = { version = "*", git = "https://github.com/DerpyCrabs/rust-osu-format" }
